### ISSUE TITLE
I cannot get the onchange event in input control

### ISSUE THREAD

**Issue by felixxu06** [craigbuckler/datalist-css#1]
After implementing this js file, my onchange function cannot be fired after selecting an item. Any update?

**Comment by craigbuckler** [comment]
It won't because the value is set in JS. You could manually trigger a change event in the `listSet()` function but...

This was written for demonstration purposes and I can't recommend using the code. That's mentioned in the readme and the associated article (https://www.sitepoint.com/html5-datalist-autocomplete/). It works but there are issues and it's largely pointless. If you need to style a `<datalist>` you'd be better off not using a `<datalist>` or waiting until vendors decide to support it!
